### ISSUE TITLE
Possibly redundant ofdm.c code

### ISSUE THREAD

**Issue by srsampson** [drowe67/codec2#149]
https://github.com/drowe67/codec2/blob/05727e601ea903a73e005884eb6ef062168647cf/src/ofdm.c#L795

I haven't compiled and tested this, but it looks like this code is redundant, as the pilots get set in the next loop.

**Comment by drowe67** [comment]
Could be ... can you pls put the proposed change in the form of a PR?  That will run all the tests.

**Comment by srsampson** [comment]
Will comply

**Comment by srsampson** [comment]
Pull completed and travis was successful.
