### ISSUE TITLE
Ctest Error  on aarch64：Required regular expression not found.Regex=[fails: 0

### ISSUE THREAD

**Issue by fubingting** [drowe67/codec2#174]
**When I execute ctest-V, the error is as follows，Does codec2 support aarch64?**

3: parse error near line 725 of file /home/all_spack_env/spack_stage/root/spack-stage-codec2-0.9.2-r7ifz3ajs54lld3zua5v4mo7ewihiby7/spack-src/octave/tcohpsk.m
3:
3:   duplicate subfunction or nested function name
3:
3: >>> function write_noise_file(raw_file_name, Fs, dopplerSpreadHz, len_samples)
3:              ^
3:
 3/26 Test  #3: test_COHPSK_modem_octave_port ..................***Failed  Required regular expression not found.Regex=[fails: 0

4: error: load: unable to find file tofdm_out.txt
4: error: called from
4:     tofdm at line 215 column 1
 4/26 Test  #4: test_OFDM_modem_octave_port ....................***Failed  Required regular expression not found.Regex=[fails: 0
]  1.23 sec
test 5
      Start  5: test_OFDM_modem_octave_port_Nc_31

5: Test command: /usr/bin/sh "-c" "NC=31 PATH_TO_TOFDM=/home/all_spack_env/spack_stage/root/spack-stage-codec2-0.9.2-r7ifz3ajs54lld3zua5v4mo7ewihiby7/spack-src/build_linux/unittest/tofdm octave --no-gui -qf /home/all_spack_env/spack_stage/root/spack-stage-codec2-0.9.2-r7ifz3ajs54lld3zua5v4mo7ewihiby7/spack-src/octave/tofdm.m"
5: Test timeout computed to be: 1500
5: warning: addpath: ~/cml/mat: No such file or directory
5: warning: called from
5:     tofdm at line 27 column 1
5: warning: addpath: ~/cml/mex: No such file or directory
5: warning: called from
5:     tofdm at line 27 column 1
5: Can't find CML mex directory so we won't run those tests for now...
5: Nc = 31 LDPC testing: 0
5: Nbitsperframe: 434
5:
5: Running C version....
5: path_to_tofdm = ../build_linux/unittest/tofdm
5: path_to_tofdm = /home/all_spack_env/spack_stage/root/spack-stage-codec2-0.9.2-r7ifz3ajs54lld3zua5v4mo7ewihiby7/spack-src/build_linux/unittest/tofdm
5: setting path from env var
5: Nc = 31
5: LDPC disabled
5: usage: /home/all_spack_env/spack_stage/root/spack-stage-codec2-0.9.2-r7ifz3ajs54lld3zua5v4mo7ewihiby7/spack-src/build_linux/unittest/tofdm [Options]:
5:   [-l --noldpc]
5:   [-n --nc NumberoFCarriers]
5: error: load: unable to find file tofdm_out.txt
5: error: called from
5:     tofdm at line 215 column 1
 5/26 Test  #5: test_OFDM_modem_octave_port_Nc_31 ..............***Failed  Required regular expression not found.Regex=[fails: 0
]  1.54 sec
test 6
      Start  6: test_COHPSK_modem_AWGN_BER

**Comment by drowe67** [comment]
So looks like this issue is related to Octave on OPs system.  I don't have access to an aarch64 system, so we'll close this issue for now. If anyone wants to work with us on ctest support for aarch64 pls feel free to repoen.
