### ISSUE TITLE
"In-place" FFT codepath is not used

### ISSUE THREAD

**Issue by nevercast** [drowe67/codec2#186]
Hello, I think this line 

https://github.com/drowe67/codec2/blob/master/src/codec2_fft.c#L141

Is meant to read

```
if (cfg->nfft <= 512)
```

Since nfft is multiplied by sizeof during the memcopy, it's safe that the 512 buffer and 512 condition be directly compared without converting into bytes.

**Comment by nevercast** [comment]
I see this is in direct contrast with the original commit https://github.com/drowe67/codec2/commit/413faeb29ceeb7167acf2a8b50e30ddf32d135d2 

So perhaps I'm mistaken in this regard.

**Comment by drowe67** [comment]
@nevercast - thanks.  :thinking: must admit I'm not sure myself.  @db4ple do you have any thoughts on this one?

**Comment by nevercast** [comment]
I was almost 100% confident until I noticed it was less of a typo and more an intentional commit.

**Comment by drowe67** [comment]
@nevercast https://github.com/drowe67/codec2/pull/187

**Comment by db4ple** [comment]
Hi, reading the comment I made I can clearly see that @nevercast is right. If it fits into the 512 element long buffer in allocated on stack, we want to use it. However, in any case, we should move the allocation of `in` inside the `if``.  
So this code needs fixing to make sense at all.

**Comment by drowe67** [comment]
Fixed in #187 thanks @nevercast and @db4ple
