### ISSUE TITLE
Including Codec 2 in an Android project

### ISSUE THREAD

**Issue by Jarvif** [drowe67/codec2#208]
Hi,drowe67:
When I integrate codec2 into Android NDK, I will be prompted with an error C: / users / jarvif / desktop / codec2ndk / APP / SRC / main / codec2 / SRC / OFDM. C: 2428: error: undefined reference to 'cabsf'. Do you know why? thank you! And someone test it in an Android NDK?

**Comment by tmiw** [comment]
cabsf is [supposed to be built into the C library](https://en.cppreference.com/w/c/numeric/complex/cabs). I'm not familiar with the NDK but perhaps there needs to be something else linked in for Android to use complex numbers?

**Comment by drowe67** [comment]
@Jarvif have you found a way to include `cabsf` on Android?

**Comment by Jarvif** [comment]
> cabsf is [supposed to be built into the C library](https://en.cppreference.com/w/c/numeric/complex/cabs). I'm not familiar with the NDK but perhaps there needs to be something else linked in for Android to use complex numbers?

maybe,thanks!

**Comment by drowe67** [comment]
This doesn't appear to be a codec2 issue, more a configuration issue for OP

**Comment by Jarvif** [comment]
> This doesn't appear to be a codec2 issue, more a configuration issue for OP
hi，drowe67 and tmiw. Codec2 in Android,must requires ANDROID MINSDK API 23+. This is because Android's NDK does not support compiling various complex.h math functions on prior API versions.See the Bionic Release Status for details. Thank you very much!

**Comment by Jarvif** [comment]
the link about Android bionic status.[https://android.googlesource.com/platform/bionic/+/master/docs/status.md](url)

**Comment by srsampson** [comment]
> Do you know why?

We don't know why, but if you figure it out let us know!

**Comment by Jarvif** [comment]
> > Do you know why?
> 
> We don't know why, but if you figure it out let us know!

 This is because Android's NDK does not support compiling various complex.h math functions on prior API versions.See the Bionic Release Status for details.the link about Android bionic status.https://android.googlesource.com/platform/bionic/+/master/docs/status.md

**Comment by Jarvif** [comment]
> > Do you know why?
> 
> We don't know why, but if you figure it out let us know!

Codec2 in Android,must requires ANDROID MINSDK API 23+.
