### ISSUE TITLE
Squelch incorrectly (?) triggers when SNR is the same as squelch level

### ISSUE THREAD

**Issue by tmiw** [drowe67/codec2#238]
I typically have my squelch in freedv-gui set to 0dB. I've noticed when a 700D signal comes in that's around 0dB SNR, the audio cuts out even though it's at the same level as the squelch. I typically need to drop the squelch down to -1 or -2 to get audio again. I'm not sure if this exists on other modes as well or if this is intended behavior; I expected squelch to kick in once the signal's below the configured level and not necessarily exactly at the level.

Anyway, figured I'd post this so there's visibility. 👍

**Comment by drowe67** [comment]
@tmiw was this resolved at the freedv-gui level?

**Comment by tmiw** [comment]
Not yet. I'll probably do it when I add some squelch changes to help with multi RX.

**Comment by tmiw** [comment]
@drowe67, I updated the current SNR display to avoid further confusion and created a PR accordingly. 👍

**Comment by drowe67** [comment]
@tmiw is it fair to say that this is not an issue with codec2, but rather something to be address in freedv-gui?

**Comment by tmiw** [comment]
Correct, I'll close.
