### ISSUE TITLE
Python -> Python3

### ISSUE THREAD

**Issue by drowe67** [drowe67/codec2#251]
It would be nice to standardise on Python3, currently a mixture of python and python3, used for various x86 and stm32 ctests.

**Comment by tmiw** [comment]
Which tests currently fail with Python3?

**Comment by drowe67** [comment]
All tests pass, as long as you install both `python` and `python3`.  This was a fresh codec2 install on a Ubuntu 20 machine.  I'm not sure if other OSs make the distinction between `python` and `python3`.

**Comment by donmr** [comment]
These days it is best to specify "python2" or "python3".  Different distros 
default plain "python" to different versions.

Don
