### ISSUE TITLE
record the sound in raw format

### ISSUE THREAD

**Issue by mahdishakeri88** [drowe67/codec2#257]
Hi dears
I want to record a sound, compress it by using Codec 2, save in a memory and decompress it again.
As you know, the acceptable format for Codec 2 is raw. How can I record a sound in the format of raw?
However, I tried to do this process, as you can see in the below. 
br=1300; arecord -f S16_LE -c 1 -r 8000 | ./src/c2enc $br - - | ./src/c2dec $br - - | aplay -f S16_LE -
But the quality of the output was very low. Is there any solution?
Tnx to all

**Comment by Posejdos** [comment]
Well, if you can hear the output and understand it, then you're probably recording it right. Try saving the recorded file on your disc and playing it, so you have a reference point depending on quality of your microphone and speakers.

Possible this is just how the codec2 performs in that bitrate.

**Comment by tmiw** [comment]
Can you try processing one of the sample files? For example, https://github.com/drowe67/codec2/blob/master/raw/ve9qrp_10s.raw. That should rule out any potential configuration issues on your end.
