### ISSUE TITLE
Export all the three version elements

### ISSUE THREAD

**Issue by marcusmueller** [drowe67/codec2#269]
cmake/version.in.h only `#define`s the first two digits.

However, SWIG has a problem with codec2/freedv_api.h that was fixed after v1.0.1, so v1.0.1 doesn't work, but v1.0.2 probably will. Sadly, we can now not test for the version, because the patchlevel is not available.

**Comment by drowe67** [comment]
@marcusmueller would a 1.03 release based on #270 fix the problem for you?

**Comment by marcusmueller** [comment]
It would indeed! Thanks!

**Comment by drowe67** [comment]
Here you go: https://github.com/drowe67/codec2/releases

**Comment by marcusmueller** [comment]
Thank you so much :)
