### ISSUE TITLE
release tag issue

### ISSUE THREAD

**Issue by chenrui333** [drowe67/codec2#273]
👋 it looks like the latest release tag is bit weird (`1.03` instead of `1.0.3`), raising this issue to confirm if it is intended. Thanks!

relates to Homebrew/homebrew-core#92107

**Comment by drowe67** [comment]
Oops no that was a mistake.  Thanks for pointing it out.  I'll try to fix it now.

**Comment by drowe67** [comment]
I think it's OK now: https://github.com/drowe67/codec2/releases

**Comment by chenrui333** [comment]
Thanks @drowe67!
