### ISSUE TITLE
assert changes value

### ISSUE THREAD

**Issue by maddin200** [drowe67/codec2#277]
[/codec2-master/src/sine.c line 62
Code:

assert((Fs == 8000) || (Fs = 16000)); // <- should Fs == 16000

**Comment by tmiw** [comment]
8000 is a valid value for Fs. See https://github.com/drowe67/codec2/blob/b002c771cebe9c39176d36b50d18a18b75d9b729/src/codec2.c#L140 for an example.

**Comment by maddin200** [comment]
of course - but Fs = 16000 is not a comparison

**Comment by drowe67** [comment]
@maddin200 thanks you are correct, I've fixed it in  f77ec1a948c7

Kind of interesting that it didn't cause a bug.  Perhaps the first condition being met (in all the 8kHz cases) caused the second not to be executed.
