### ISSUE TITLE
Definition different from Declaration

### ISSUE THREAD

**Issue by maddin200** [drowe67/codec2#312]
src/gp_interleaver.h line 38 / 39 vs src/gp_interleaver.c line 90 / 100
void gp_interleave_float(float frame[], float interleaved_frame[], int Nbits);

void gp_interleave_float(float interleaved_frame[], float frame[], int Nbits) {

void gp_deinterleave_float(float interleaved_frame[], float frame[], int Nbits);

void gp_deinterleave_float(float frame[], float interleaved_frame[], int Nbits) {

**Comment by drowe67** [comment]
Thanks @maddin200 - can you please post a Pull Request to fix this issue?

**Comment by maddin200** [comment]
fixed
