### ISSUE TITLE
cloning a certain branch will clone "master" files

### ISSUE THREAD

**Issue by cybork42** [drowe67/codec2#320]
Maybe this is no real issue, but rather an imrpovement suggestion, or even a nonsense idea. When you execute

`git clone --branch ms-2020-experiment https://github.com/drowe67/freedv-gui.git`

you get what you expect, all source files from that named branch. However and naturally, the build scripts know nothing about being in a branch and still say  

`git clone https://github.com/drowe67/freedv-gui.git`

An improvement suggestion might be to have the build scripts look at the `.git` file and identify which branch was requested and rather use files from that branch rather than `master` when cloning anew?

**Comment by tmiw** [comment]
As this is a freedv-gui specific issue, I'm going to close this issue and direct all further discussion to https://github.com/drowe67/freedv-gui/issues/232.
