### ISSUE TITLE
FSK: cannot demodulate signal with SymbolFreq=300 and TxFreqSpace=200 

### ISSUE THREAD

**Issue by sh123** [drowe67/codec2#343]
Hello.

Trying to use FSK modulator/de-modulator to modulate and demodulate HF packet 300 signal.

Modulator works correctly (software such as Direwolf can de-modulate it), but de-modulator fails to de-modulate own samples.

This test works when TEST_FRAME_SIZE equals 100, but fails when TEST_FRAME_SIZE is set to 1000 (i think it starts failing from second samples chunk).
```
./fsk_get_test_bits - 10000 1000 | ./fsk_mod 2 19200 300 1600 200 - - | ./fsk_demod 2 19200 300 - - | ./fsk_put_test_bits - 1000
Setting estimator limits to 0 to 9600 Hz.
Using custom frame size of 1000 bits
[0000] BER 0.500, bits tested      0, bit errors      0
FAIL
```
it starts working BER free from about RxFreqSpace=240, which is about 80% from SymbolFreq.

Is this limitation by design or some fault? What is the the minimum BER free ratio between RxFreqSpace and SymbolFreq? Is it possible to tweak fsk.c to get it working?

**Comment by drowe67** [comment]
It's a by product of design.  This demod uses an "ideal non-coherent" design, which has filters for each tone are like two discrete Fourier transform bins next to each other.  This requires a tone separation of at least Rs=300 between tones, or the filter will overlap and interfere with each other.

As an aside, the physics of FSK also says the BER versus SNR performance will be poor if tone separation < Rs, however some protocols (e.g. DMR/P25) and (I guess HF packet 300) do this to save bandwidth.

I can't think of any easy change to get the demod to work in this case.
