### ISSUE TITLE
codec run in android 4.4

### ISSUE THREAD

**Issue by smilingacan** [drowe67/codec2#346]
Android Project run in android 6.0 (sdk > 23) is OK。When I compile codec2 with minSDK 19 for  android 4.4，complex.h is not recognized。
note: include the header <complex.h> or explicitly provide a declaration for 'cimagf'
  E:/Project/jni/code4/app/src/main/codec2/src/ofdm.c:2491: error: undefined reference to 'cabsf'
  E:/Project/jni/code4/app/src/main/codec2/src/ofdm.c:2491: error: undefined reference to 'cabsf'
  E:/Project/jni/code4/app/src/main/codec2/src/ofdm.c:2491: error: undefined reference to 'cabsf'
  E:/Project/jni/code4/app/src/main/codec2/src/ofdm.c:1590: error: undefined reference to 'conjf'
  E:/Project/jni/code4/app/src/main/codec2/src/ofdm.c:1597: error: undefined reference to 'cargf'
  E:/Project/jni/code4/app/src/main/codec2/src/ofdm.c:1679: error: undefined reference to 'cabsf'
  E:/Project/jni/code4/app/src/main/codec2/src/ofdm.c:1629: error: undefined reference to 'conjf'
  E:/Project/jni/code4/app/src/main/codec2/src/ofdm.c:1629: error: undefined reference to 'conjf'
  E:/Project/jni/code4/app/src/main/codec2/src/ofdm.c:1629: error: undefined reference to 'conjf'
  E:/Project/jni/code4/app/src/main/codec2/src/ofdm.c:1673: error: undefined reference to 'cargf'
  E:/Project/jni/code4/app/src/main/codec2/src/ofdm.c:1657: error: undefined reference to 'cargf'
  E:/Project/jni/code4/app/src/main/codec2/src/ofdm.c:1708: error: undefined reference to 'cargf'。

Is there any solutions to solve the problem?

**Comment by tmiw** [comment]
A few things:

1. We should probably keep everything in one issue. Can #345 be closed?
2. Android 4.4 is pretty old at this point. Is there a reason why it needs to be supported? Based on https://www.crystax.com/en/android/ndk it seems that complex.h requires Android 5 at minimum unless you use Crystax's NDK instead of Google's, so there might not be much we can do on Codec2.
