### ISSUE TITLE
Delete 1.03 tag?

### ISSUE THREAD

**Issue by ryantm** [drowe67/codec2#349]
I run a bot that automatically updates packages in nixpkgs and it is getting confused by this repository because there is a 1.03 tag, which  it thinks is the highest semantic version. Do you think you could delete that tag?

https://github.com/drowe67/codec2/releases/tag/v1.03

Example of bad update: https://github.com/NixOS/nixpkgs/pull/186237

If not, feel free to close. Thank you!

**Comment by drowe67** [comment]
Thanks @ryantm - that tag has been deleted
