### ISSUE TITLE
Frequency readout in 800xa is reversed

### ISSUE THREAD

**Issue by DG9BFC** [drowe67/codec2#370]
title says it .. the frequency redout in 800xa is wrong
when i worked fullduplex over qo100 and tested the different modes i have found out that the 800xa shows the frequency wrong
as a test i set my TX 180Hz HIGHER ... mode 1600 shows PLUS 180 offset while 800xa shows MINUS 180Hz
so in all modes the offset is shown but in 800xa (there the "fault" is shown)
in the two screenshots you see that the tx frequency is higher (or the rx is LOW)
i used usb in both cases and as can be seen signal is shifted to right (higher tones)
800xa shows fault (-180) and other modes show where to tune (+180) to get to 0Hz offset ... one is wrong ;-)
![freedv_800xa_tx_plus180hz](https://user-images.githubusercontent.com/17382592/209653122-11ac4da9-d488-47a3-a554-d4ab0211e3f8.jpg)
![freedv_1600_tx_plus180hz](https://user-images.githubusercontent.com/17382592/209653125-613e3c60-52e2-4ea6-9237-9581350dc937.jpg)

**Comment by drowe67** [comment]
Thanks @DG9BFC - I think I've fixed it.  It's also interesting to know the use cases for FreeDV, I was wondering if 1600 was in use.

@tmiw - it might be useful to compile a list of use cases for FreeDV, e.g. what modes are used where.  Useful input for development and maintenance.

**Comment by DG9BFC** [comment]
hi david .. welcome :-)
i would like to have the levels between the modes more even  but thats a different thingy .. a new release to try ??
about modes ... qo100 is a linear transponder so as long as your station is stable on receive and transmit any freedv mode does work
and cause we all use fullduplex (or should use) you can hear what your qso partner hears (easy to test all modes without a partner or without a websdr involved)
the lnb may add some frequency varation (slight wobble) so modes where a pilot tone is added or were the mode itself is immune to those slight varations work best ... if you need some recordings (or screenshots like above) ... just ask

**Comment by DG9BFC** [comment]
sidenote ... with 800xa i can easier drive my station to higher power and get the highest snr reports over the bird (about 20db max) while other modes are more in the 10 to 12 db range

**Comment by drowe67** [comment]
Yes 800XA is FSK, so PAPR=0dB, you get the most out of your PA.

**Comment by DG9BFC** [comment]
i wait for mooneer for a next test version ... then do further testing
not only that i CAN drive it higher but it IS higher from the soft towards sdr soft
![Screenshot-2022-12-24-222611](https://user-images.githubusercontent.com/17382592/209727578-1894dcb8-d82f-43a4-ba1d-9744c111e6b8.jpeg)
![Screenshot-2022-12-24-222631](https://user-images.githubusercontent.com/17382592/209727583-7b842832-24c5-48a8-9088-5f515cd89b5d.jpeg)
here with reduced power
![Screenshot-2022-12-24-220419](https://user-images.githubusercontent.com/17382592/209727683-99918682-274d-4992-b6c7-3886ffba486b.jpeg)
![Screenshot-2022-12-24-220445](https://user-images.githubusercontent.com/17382592/209727696-5bef7a35-928f-4968-8cb0-162a235bd874.jpeg)
and here with higher output

**Comment by DG9BFC** [comment]
as can be seen 800xa is much higher

**Comment by DG9BFC** [comment]
a 10 db higher power on the 1600 (and other modes) would make the power more even (so comparing modes would be easier)

**Comment by tmiw** [comment]
> @tmiw - it might be useful to compile a list of use cases for FreeDV, e.g. what modes are used where. Useful input for development and maintenance. Perhaps something we can discuss at PLT, give the range of experience of the team.

FWIW, 800XA and 1600 seem to be mostly used on linear satellites these days while 700D and E seem to be the most common day to day modes on HF.

**Comment by drowe67** [comment]
I guess it's the ability to handle large and rapidly changing frequency offsets.

**Comment by tmiw** [comment]
> I guess it's the ability to handle large and rapidly changing frequency offsets.

At least in the case of 1600, the center carrier is much easier to track during a satellite pass for Doppler adjustment purposes. :)

**Comment by drowe67** [comment]
@tmiw - Would you agree this one is closed?

**Comment by tmiw** [comment]
> @tmiw - Would you agree we can close this one?

Yep 👍

**Comment by DG9BFC** [comment]
yes ... readout is fixed
thank you 
dg9bfc sigi
