### ISSUE TITLE
Uninitialized variable in ofdm.c :: ofdm_complex_dot_product()

### ISSUE THREAD

**Issue by SoftwareToolworks** [drowe67/codec2#387]
At line 698:

https://github.com/drowe67/codec2/blob/master/src/ofdm.c#L698

result is not set here to complex 0.0

This doesn't fail if ```USE_VECTOR_OPS``` or ```__EMBEDDED__``` is defined, but falling through past those options, the variable is then added to in a loop.

So ```result``` being an automatic variable has undefined contents.

From the GNU C Manual:

https://github.com/VernonGrant/gnu-c-language-manual/blob/main/markdown/Local-Variables.md

__Warning__: If the declaration of an automatic variable does not specify an initial value, the variable starts out containing __garbage__.

**Comment by tmiw** [comment]
Thanks @SoftwareToolworks! I opened PR #388 to resolve this issue.
