### ISSUE TITLE
Is it possible to use STM32WLE5CCU6 microcontroller with codec2 ?

### ISSUE THREAD

**Issue by happytm** [drowe67/codec2#390]
Is it possible to use STM32WLE5CCU6 microcontroller with codec2 ? tthe datasheet for microcontroller is below:

https://www.st.com/resource/en/datasheet/stm32wle4jc.pdf

The benefit of using this chip is it has built in LoRa radio and it has few 12 bit ADC and single 12 bit DAC. 

Thanks.

**Comment by drowe67** [comment]
It has enough RAM and Flash but I can't tell if if has FPU or what the clock speed it runs.  So we need a FPU and (I'm guessing) 80MHz CPU for just the codec.

**Comment by tmiw** [comment]
If ST is anything like Espressif, if it's not mentioned in the datasheet it doesn't exist unfortunately. (FPU)

**Comment by happytm** [comment]
Thank you for your quick replies guys.
