### ISSUE TITLE
Spectral amplitude quantization?

### ISSUE THREAD

**Issue by moseranliunian** [drowe67/codec2#398]
I would like to know how to extract harmonic number L and sample it to mel scale under the working mode of 700c and 450 of codec 2. And the vector quantization at the end? Is there an algorithm formula or programming document, a paper? I would really appreciate it if you could clear it up.

**Comment by drowe67** [comment]
Take a look at sine.c, c2sim is useful for this sort of experimentation.  You'll need to study the code., Here is a blog post on [codec2 700c](https://www.rowetel.com/wordpress/?p=5373)
