### ISSUE TITLE
the robustness to the single bit error?

### ISSUE THREAD

**Issue by moseranliunian** [drowe67/codec2#399]
Sorry to bother you, but I would like to ask one more question about codebook sorting. It is embodied in what method is adopted to achieve the robustness to the single bit error  in 450bps ? And in what programming files is the calculation of the quality factor Q represented? Or is there a picture?

**Comment by drowe67** [comment]
Could you please post these questions to Discussions?  They are not actually Issues with Codec 2 that need fixing.

This blog post https://www.rowetel.com/?p=7837 has references to papers on index sorting.

**Comment by moseranliunian** [comment]
Oh, I'm really sorry. Since this is the first time for me to learn about voice codec and GitHub, I am not very familiar with some relevant regulations
