### ISSUE TITLE
Using the fsk modem in external projects? fsk_api.c / fsk_api.h needed?

### ISSUE THREAD

**Issue by xssfox** [drowe67/codec2#42]
Hey team,

I've been playing with using the fsk.h and fsk library from libcodec2 for my [selcall project](https://github.com/xssfox/freeselcall). It's been working great as a modem for the project - many thanks for providing it.

I'm aware that this library likely isn't intended to be used in other projects like this. At the moment the usage is quite clunky, getting the user to compile libcodec2 from source and then setting `CFLAGS="-I/path/to/codec2/src` - this is because `kiss_fftr.h` isn't included in the installed header files when doing `make install`

I am wondering about the best way to approach this problem. Some options I see working are:
- codec2 add `kiss_fftr.h` to the files exported to `/usr/local/include/codec2`
- codec2 could provide an `_api` version of fsk, similar to the `freedv_api` approach which seems to work ok
- I could vendor'ize the fsk specific components into my project

Thoughts?

**Comment by tmiw** [comment]
I don't recall if Codec2 made any changes to `kiss_fft*` but is it possible that including the https://github.com/mborgerding/kissfft project into your own project might work?

**Comment by drowe67** [comment]
@xssfox sounds like a cool project.  Given it's [prototype code](https://github.com/xssfox/freeselcall#freeselcall) using libcodec2 outside of it's intended use cases, your current solution sounds fine.  As per the codec 2 [README](https://github.com/drowe67/codec2#pull-requests-feature-requests) support for one off or experimental projects is best done outside of libcodec2.

**Comment by xssfox** [comment]
I've ended up adding codec2 as a git submodule and adjusted the build process to static link against it which somewhat solves my problems with distribution in the near term.

I think it might still be worth considering make fsk into something that could be easily included into other projects as it's a useful library to use for fsk modulation and demodulation. It's already in use not only in my project but horusdemodlib and likely others.

**Comment by drowe67** [comment]
@xssfox - good to see you have a way fwd.

We're happy to consider you proposal - please free free to submit a [feature request form](https://freedv.org/wp-content/uploads/sites/8/2024/03/FreeDV-027-Feature-Request-Form-V1.1.pdf).
