### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by a897456** [drowe67/codec2#52]
(base) rian0532@DESKTOP-PQV8NDO:/mnt/e/000/codec2/build_linux$ aplay -f S16_LE hts1a_c2_2400.raw
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
aplay: main:831: audio open error: No such file or directory

**Comment by tmiw** [comment]
Does something like this work for you?

```
(base) rian0532@DESKTOP-PQV8NDO:/mnt/e/000/codec2/build_linux$ aplay -f S16_LE ../raw/hts1.raw
```

If not, I'd suspect a sound device issue on your local PC based on the error messages you've provided.

**Comment by a897456** [comment]
(base) rian0532@DESKTOP-PQV8NDO:/mnt/e/000/codec2/build_linux$ aplay -f S16_LE ../raw/hts1.raw
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
aplay: main:831: audio open error: No such file or directory

The same problem

**Comment by a897456** [comment]
Can I change the output file (such like `hts1a_c2_2400.raw`) to a file (such like `hts1a_c2_2400.wav`) that the system can play?

**Comment by tmiw** [comment]
I just tested on Ubuntu 22.04 and I'm able to play raw files with no problems:

```
parallels@ubuntu-linux-22-04-desktop:~/freedv-gui/codec2/raw$ aplay -f S16_LE hts1.raw 
Playing raw data 'hts1.raw' : Signed 16 bit Little Endian, Rate 8000 Hz, Mono
^CAborted by signal Interrupt...
aplay: pcm_write:2127: write error: Interrupted system call
parallels@ubuntu-linux-22-04-desktop:~/freedv-gui/codec2/raw$
```

You can try converting to WAV using something like Audacity or sox but I suspect you're going to run into the (likely) same local configuration issue that you'e running into now.
