### ISSUE TITLE
Contrast experiment

### ISSUE THREAD

**Issue by a897456** [drowe67/codec2#53]
http://www.rowetel.com/?page_id=452
In the comparison experiment, you mentioned a lot of encoders, could you please provide links, I want to use them too. THS
`MELPe 2400 bit/s` `LPC-10 2400 bit/s`  `MELPe 600 bit/s`  `AMBE 2000 bit/s`...

**Comment by tmiw** [comment]
Not sure about MELPe but locations for many of the rest are mentioned in the blog post:

> The AMBE samples were generated using a [DV-Dongle](http://www.dvdongle.com/), a USB device containing the DVSI AMBE2000 chip. The LPC-10 samples were generated using the [Spandsp](http://www.soft-switch.org/) library.

**Comment by a897456** [comment]
> > The AMBE samples were generated using a [DV-Dongle](http://www.dvdongle.com/), a USB device containing the DVSI AMBE2000 chip. The LPC-10 samples were generated using the [Spandsp](http://www.soft-switch.org/) library.

Yes, but through the device such like USB device, it's not practical for me, I just want to implement these bit rates through code for comparison experiments, and I can't find any good code on github.

**Comment by tmiw** [comment]
> > > The AMBE samples were generated using a [DV-Dongle](http://www.dvdongle.com/), a USB device containing the DVSI AMBE2000 chip. The LPC-10 samples were generated using the [Spandsp](http://www.soft-switch.org/) library.
> 
> Yes, but through the device such like USB device, it's not practical for me, I just want to implement these bit rates through code for comparison experiments, and I can't find any good code on github.

AMBE has traditionally been patent encumbered (and the D-Star variant only recently went out of patent), which likely explains why there's no easily available software-only implementation.

**Comment by a897456** [comment]
Has codec2 published any papers？I used `codec2` as the keyword, but I didn't find the paper

**Comment by drowe67** [comment]
1. Links on https://www.rowetel.com/wordpress/?page_id=452
2. doc/codec2.pdf

**Comment by a897456** [comment]
I'm sorry, I mean has codec2 been published in journals or conferences.

**Comment by drowe67** [comment]
No
