### ISSUE TITLE
memory affect in decoder

### ISSUE THREAD

**Issue by programmer131** [drowe67/codec2#55]
Using single codec2 instance, while trying to decode two streams of encoded voice from two different transmitters, decoded voice gets jitters/jerks/clutters, but if we setup two codec2 instances like this at receiver end 
```
struct CODEC2 *c2_1 = codec2_create(CODEC2_MODE_3200);
struct CODEC2 *c2_2 = codec2_create(CODEC2_MODE_3200);
```
it solves the problem, 
Is this expected behavior or I'm missing something here
![decoder-problem](https://github.com/drowe67/codec2/assets/12946496/448616ed-37d5-437c-99bd-a66867e289ab)

**Comment by drowe67** [comment]
This is expected behavior, you need a separate instance for each stream.
