### ISSUE TITLE
.bit in binary

### ISSUE THREAD

**Issue by alwinhb** [drowe67/codec2#61]
I am able to input my voice and get the equivalent .bit file further I am able to convert it into .raw using this code.

I can also hear .raw file after the conversion from .bit file.

I want .bit in the form of 0/1 is there any possibility for the same? As of now the .bit file is non-readable. 

@jimt @tmiw @majbthrd @drowemyriota @lukasostendorf

**Comment by tmiw** [comment]
IIRC I can't think of anything offhand in codec2 that will do this, but you can always view the file using `xxd`:

```
$ xxd -b file.bit
00000000: 11001010 11111110 10111010 10111110 00000000 00000000  ......
00000006: 00000000 00000010 00000001 00000000 00000000 00000111  ......
...
$
```

**Comment by alwinhb** [comment]
Thanks @tmiw it worked!
