### ISSUE TITLE
cmake  question  

### ISSUE THREAD

**Issue by oystercatcher** [drowe67/codec2#72]
trying to compile  codec2    for  sdrangel   on fedora 30

when I run cmake it completes but I am wondering if I am missing something
all the msgs about missing  math functions?

cmake -Wno-dev -DCMAKE_INSTALL_PREFIX=/opt/install/codec2 ..
-- The C compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- codec2 version: 0.9
-- Performing Test COMPILER_SUPPORTS_GNU11
-- Performing Test COMPILER_SUPPORTS_GNU11 - Success
-- Performing Test COMPILER_SUPPORTS_GNU99
-- Performing Test COMPILER_SUPPORTS_GNU99 - Success
-- Found Git: /usr/bin/git (found version "2.21.0") 
-- Codec2 current git hash: 76a20416
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Looking for __GNU_LIBRARY__
-- Looking for __GNU_LIBRARY__ - found
-- Looking for floor
-- Looking for floor - not found
-- Looking for ceil
-- Looking for ceil - not found
-- Looking for pow
-- Looking for pow - not found
-- Looking for sqrt
-- Looking for sqrt - not found
-- Looking for sin
-- Looking for sin - not found
-- Looking for cos
-- Looking for cos - not found
-- Looking for atan2
-- Looking for atan2 - not found
-- Looking for log10
-- Looking for log10 - not found
-- Looking for round
-- Looking for round - not found
-- Looking for getopt
-- Looking for getopt - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Threads library flags: -lpthread
-- Build type is: Debug
-- Compiler Flags:  -Wall -Wno-strict-overflow -std=gnu11 -fPIC-g -O2
-- Libraries linked: 
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/build/codec2/build_linux

**Comment by hobbes1069** [comment]
It is looking for functions it needs that it can't find. I don't know anything about sdrangel so they could be there and cmake just needs some hints on where to look or they could be missing. 

Either way general discussion and support is handled on the Digital Voice mailing list and not through github issues. 

http://groups.google.com/group/digitalvoice/

Thanks!
