### ISSUE TITLE
Won't install on latest debian.

### ISSUE THREAD

**Issue by citynetcomputing** [drowe67/codec2#78]
cc: error: unrecognized command line option ‘-no-pie’

**Comment by srsampson** [comment]
What is the output of:

gcc -Q -v

**Comment by drowe67** [comment]
@citynetcomputing can you please give us some more information on this issue?  is it an installation or build issue?  What is the output from make?

**Comment by jimt** [comment]
See also #146

**Comment by srsampson** [comment]
Not enough information, no response to adding details.
