### ISSUE TITLE
CMake requires SVN

### ISSUE THREAD

**Issue by donmr** [drowe67/codec2#9]
In the top level CMakeLists.txt is code that gets the SVN version.  If you checkout from GIT into a new directory where SVN has not been used, AND it is named codec2-dev, then cmake gets an error:

CMake Error at /usr/share/cmake-3.10/Modules/FindSubversion.cmake:99 (message):
  Command "/usr/bin/svn info
  /home/don/Radio/Digital/FreeDV/Source/Git/codec2-dev" failed with output:

  svn: E155007: '/home/don/Radio/Digital/FreeDV/Source/Git/codec2-dev' is not
  a working copy

**Comment by hobbes1069** [comment]
Yup, still some cleanup to do after the move. I'll take a look.

**Comment by hobbes1069** [comment]
I'm not sure if it really does anything useful at this point but I have updated it to show the git short commit hash.

**Comment by donmr** [comment]
Fixed
